version: '3.7'
services:
  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress
    container_name: wp-wordpress
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - /efs/website:/var/www/html
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      WORDPRESS_DB_HOST: dbuasfix.cjz0330jghb7.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_CONFIG: wp_